version: "3.8"
services:       
  dbmanager:
    container_name: local_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    networks:
      - proxy
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgadmin.service=pgadmin"
        - "traefik.http.routers.pgadmin.entrypoints=websecure"
        - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.local`)"
        - "traefik.http.routers.pgadmin.tls=true"
        - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
networks:
  proxy:
    external: true